apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-connector
  labels:
    app: multi-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-connector
  template:
    metadata:
      labels:
        app: multi-connector
    spec:
      containers:
      - name: multi-connector
        image: eenemanoy/multi-connector:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: smartwatcher-config
            mountPath: /usr/src/app/config/eeneman-senaatti.json
            subPath: smartwatcher.json
          - name: kerava-indoor-config
            mountPath:  /usr/src/app/config/eeneman-iisy-kerava-1.json
            subPath: kerava-indoor.json
          - name: luotettava-kumppani-report-pdf-config
            mountPath:  /usr/src/app/config/eeneman-luotettava-kumppani-report-pdf.json
            subPath: luotettava-kumppani-report-pdf.json
          - name: vilpe-config
            mountPath:  /usr/src/app/config/eeneman-vilpe.json
            subPath: vilpe.json
      volumes:
        - name: smartwatcher-config
          configMap:
            name: smartwatcher-config
        - name: kerava-indoor-config
          configMap:
            name: kerava-indoor-config
        - name: luotettava-kumppani-report-pdf-config
          configMap:
            name: luotettava-kumppani-report-pdf-config
        - name: vilpe-config
          configMap:
            name: vilpe-config
---
apiVersion: v1
kind: Service
metadata:
  name: multi-connector
  labels:
    app: multi-connector
spec:
  selector:
    app: multi-connector
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
