apiVersion: v1
data:
  kerava-indoor.json: |-
    {
        "template": "kerava-indoor",
        "static": {
            "url": "https://iisycloud.fi/rest/",
            "email": "",
            "password": ""
        },
        "dynamic": {
            "authConfig.body": [
                "ids",
                "startTime",
                "endTime",
                "dataTypes"
            ]
        },
        "request": {
            "ids": [
               {
                 "idOfLocation": "<idOfLocation>",
                 "idOfSensor": "<idOfSensor>"
               }
            ]
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kerava-indoor-config
