apiVersion: v1
data:
  luotettava-kumppani-report-pdf.json: |
    {
        "template": "luotettava-kumppani-report-pdf",
        "static": {
          "url": "https://noutaja.tilaajavastuu.fi/",
          "username": "",
          "password": ""
        },
        "dynamic": {
          "authConfig.path": ["registrationCountry", "idOfficial"]
        },

        "request": {
            "registrationCountry":"<parameters.registrationCountry>",
            "idOfficial":"<parameters.idOfficial>"
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: luotettava-kumppani-report-pdf
