apiVersion: v1
data:
  smartwatcher.json: |-
    {
        "template": "smartwatcher",
        "static": {
            "url": "https://smartwatcher.northeurope.cloudapp.azure.com:4443/",
            "email": "",
            "password": ""
        },
        "dynamic": {
            "authConfig.path": [
              "ids",
              "startTime",
              "endTime",
              "dataTypes"
            ]
        },
        "request": {
            "ids": [
                {
                    "id": "<id>",
                    "dataTypes": "<dataType>"
                }
            ]
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: smartwatcher-config
