apiVersion: v1
data:
  vilpe.json: |-
    {
      "template": "vilpe",
      "static": {
          "url": "https://sense-api.vilpe.com",
          "UserPoolId": "",
          "ClientId": ""
      },
      "dynamic": {
          "authConfig.path": [
              "ids"
          ],
          "authConfig.username":"authCredentials.username",
          "authConfig.password":"authCredentials.password"
      },
      "request": {
          "ids": [
              {
                  "id": "<id>"
              }
          ]

      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: vilpe-config
